### ISSUE TITLE
arg mismatch in SetWindowShouldClose

### ISSUE THREAD

**Issue by PinkMushroom** [Gnimuc/Videre#7]
I tried to make sure I found all of these in my changes but it looks like i missed several. That's what i get for not doing `grep -r`, lol.

ERROR: LoadError: MethodError: no method matching SetWindowShouldClose(::GLFW.Window, ::UInt32)
Closest candidates are:
  SetWindowShouldClose(::GLFW.Window, !Matched::Bool) at /home/briand/.julia/packages/GLFW/g1nX6/src/glfw3.jl:502

the last arg needs to be a julia 'true' value.  Here's a list of the rest of the files which have the bug.  I'm happy to do another PR, but i figure it's just as easy for you to make the changes.  However, if not, let me know and i'll create a PR.

7_alpha_blending/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)
24_gui_panels/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)
22_geom_shaders/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)
16_frag_reject/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)
19_fog/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)
18_spotlights/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)
23_tessellation_shaders/glutils.jl:	key == GLFW.KEY_ESCAPE && action == GLFW.PRESS && GLFW.SetWindowShouldClose(window, GL_TRUE)

**Comment by Gnimuc** [comment]
nice catch! fixed on master now, thanks!
